{
  "widgets":[{
    "type":"text",
    "x":0,
    "y":6,
    "width":12,
    "height":3,
    "properties": {
      "markdown":"## EC2 metrics \\nEC2 instances can be administrated via ssm only:\\n``` \\naws ssm start-session --target <instance-id>\\n``` "
      }
    },{
      "type":"metric",
      "x":0,
      "y":3,
      "width":7,
      "height":3,
      "properties":{
        "view":"singleValue",
        "metrics":[[
          "AWS/AutoScaling",
          "GroupTotalInstances",
          "AutoScalingGroupName",
          "webserver"
        ],[
          ".",
          "GroupInServiceInstances",
          ".",
          "."
        ]],
        "region":"eu-central-1",
        "stacked":false,
        "setPeriodToTimeRange":false,
        "liveData":true,"sparkline":true
      }
    },{
      "type":"text",
      "x":0,
      "y":0,
      "width":24,
      "height":3,
      "properties":{
        "markdown":"# My Webpage\\nA [link](https://learning.is4it.dev.sqfy.io) to my webpage.\\nThis is the awesome dashboard for the health of my first webpage.\\n## Autoscaling group\\nOverview over my autoscaling"
      }
    },{
      "type":"metric",
      "x":7,
      "y":3,
      "width":17,
      "height":3,
      "properties":{
        "view":"timeSeries",
        "stacked":false,
        "metrics":[[
          "AWS/AutoScaling",
          "GroupInServiceInstances",
          "AutoScalingGroupName",
          "webserver"
        ]],
        "region":"eu-central-1"
      }
    },{
      "type":"metric",
      "x":0,
      "y":9,
      "width":6,
      "height":6,
      "properties":{
        "view":"timeSeries",
        "metrics":[[
          "AWS/EC2",
          "CPUUtilization",
          "InstanceType",
          "t3.micro"
        ]],
        "region":"eu-central-1",
        "stacked":false,
        "title":"Aggregated CPU usage"
      }
    },{
      "type":"metric",
      "x":6,
      "y":9,
      "width":6,
      "height":6,
      "properties":{
        "view":"singleValue",
        "stacked":false,
        "metrics":[[
          "AWS/EC2",
          "NetworkIn"
        ],[
          ".","NetworkOut"
        ]],
        "region":"eu-central-1",
        "setPeriodToTimeRange":true
      }
    }
  ]
}