
variable "httpdVersion" {
  type    = string
  default = "2.4.46"
}

variable "phpVersion" {
  type    = string
  default = "7.4"
}

data "amazon-ami" "autogenerated_1" {
  filters = {
    name                = "amzn2-ami-hvm-2.0.*-x86_64-gp2"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["137112412989"]
  region      = "eu-central-1"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  ami_name                    = "website_ami_${local.timestamp}"
  associate_public_ip_address = "true"
  instance_type               = "t3.large"
  region                      = "eu-central-1"
  source_ami                  = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username                = "ec2-user"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline         = ["sudo yum -y update",
                      "sudo yum install -y php-fpm php-mysql",
                      "sudo amazon-linux-extras install -y nginx1"]
    inline_shebang = "/bin/bash -e"
  }

  provisioner "shell" {
    inline         = [ <<EOS
sudo echo "map \$http_user_agent \$keeplog {
\"ELB-HealthChecker/2.0\" 0;
default 1;
}
server {
listen   8080;
error_log /var/log/nginx/web_error.log;
access_log /var/log/nginx/web_access.log combined if=\$keeplog;
root /srv/data;
index index.php;
location / {
try_files \$uri \$uri/ /index.php;
}
# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
location ~ \.php$ {
try_files \$uri =404;
fastcgi_pass 127.0.0.1:9000;
fastcgi_index index.php;
fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
include fastcgi_params;
}
}" > /tmp/default.conf
EOS
    ]
    inline_shebang = "/bin/bash -e"
  }

  provisioner "shell" {
    inline         = ["sudo mv /tmp/default.conf /etc/nginx/conf.d/default.conf",
                      "sudo systemctl enable nginx",
                      "sudo systemctl enable php-fpm",
                      "sudo mkdir /srv/data"]
    inline_shebang = "/bin/bash -e"
  }

}
